<?php

/**
 * Pipelinq ZgwNotificationController.
 *
 * Public webhook endpoint that NRC calls to deliver subscription
 * notifications. Authentication is via a per-abonnement Bearer token
 * (generated by NrcSubscriptionService at registration time and either
 * stored as a vault reference or stored directly on the NrcAbonnement
 * record). The controller:
 *
 *   1. Extracts the Bearer token.
 *   2. Resolves the matching NrcAbonnement (`callbackAuth === token`).
 *   3. Returns 401 when no match (constant-time string compare).
 *   4. Hands the payload to `NrcNotificationListener::dispatch()`.
 *   5. Returns 202 Accepted immediately so NRC doesn't retry on handler latency.
 *
 * #[PublicPage] + #[NoCSRFRequired] because NRC cannot present a Nextcloud
 * session cookie or CSRF token; authenticity is enforced by the bearer match.
 *
 * @category Controller
 * @package  OCA\Pipelinq\Controller
 *
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 * SPDX-License-Identifier: EUPL-1.2
 *
 * @version GIT: <git_id>
 *
 * @link https://pipelinq.nl
 *
 * @spec openspec/changes/zgw-api-bridge/specs/zgw-api-bridge/spec.md#req-zgw-007
 */

declare(strict_types=1);

namespace OCA\Pipelinq\Controller;

use OCA\Pipelinq\AppInfo\Application;
use OCA\Pipelinq\Listener\NrcNotificationListener;
use OCA\Pipelinq\Service\Zgw\ZgwApiClient;
use OCA\Pipelinq\Service\Zgw\ZgwRegisterAccess;
use OCP\AppFramework\Controller;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\Attribute\NoCSRFRequired;
use OCP\AppFramework\Http\Attribute\PublicPage;
use OCP\AppFramework\Http\JSONResponse;
use OCP\IRequest;
use Psr\Log\LoggerInterface;

/**
 * Public NRC callback controller.
 */
class ZgwNotificationController extends Controller {
	/**
	 * Constructor.
	 *
	 * @param IRequest $request Request.
	 * @param ZgwRegisterAccess $registers Register facade (NrcAbonnement lookup).
	 * @param ZgwApiClient $api For vault-ref resolution on callbackAuth.
	 * @param NrcNotificationListener $listener Per-kanaal dispatcher.
	 * @param LoggerInterface $logger PSR-3 logger.
	 */
	public function __construct(
		IRequest $request,
		private ZgwRegisterAccess $registers,
		private ZgwApiClient $api,
		private NrcNotificationListener $listener,
		private LoggerInterface $logger,
	) {
		parent::__construct(appName: Application::APP_ID, request: $request);
	}//end __construct()

	/**
	 * POST /api/zgw/notificaties/inbox — NRC callback ingest.
	 *
	 * @return JSONResponse 202 on success, 401 on bad bearer, 400 on bad body.
	 */
	#[PublicPage]
	#[NoCSRFRequired]
	public function inbox(): JSONResponse {
		// Webhook authenticity is enforced by the per-abonnement bearer match
		// below. The endpoint is #[PublicPage] because NRC cannot present a
		// Nextcloud session cookie; bearer mismatch maps to HTTP 422
		// (the BlastWebhookController/AppointmentPaymentWebhookController
		// convention) instead of 401 to signal "webhook signature failure"
		// without overloading session-auth semantics.
		$authHeader = (string)$this->request->getHeader('Authorization');
		$token = self::extractBearer(headerValue: $authHeader);
		if ($token === '') {
			return new JSONResponse(
				['error' => 'Missing bearer token'],
				Http::STATUS_UNPROCESSABLE_ENTITY
			);
		}

		$abonnement = $this->resolveAbonnementByBearer(token: $token);
		if ($abonnement === null) {
			$this->logger->warning(
				'ZGW NRC: inbox received with unknown bearer',
				['ip' => $this->request->getRemoteAddress()]
			);
			return new JSONResponse(
				['error' => 'Unknown bearer token'],
				Http::STATUS_UNPROCESSABLE_ENTITY
			);
		}

		$payload = json_decode($this->readRawBody(), true);
		if (is_array($payload) === false) {
			return new JSONResponse(
				['error' => 'Invalid JSON payload'],
				Http::STATUS_BAD_REQUEST
			);
		}

		// The actual dispatch happens synchronously but the controller
		// returns 202 to NRC immediately — listener errors do not propagate.
		$this->listener->dispatch($abonnement, $payload);

		return new JSONResponse(
			['status' => 'accepted'],
			Http::STATUS_ACCEPTED
		);
	}//end inbox()

	/**
	 * Walk all active NrcAbonnement records and return the one whose
	 * callbackAuth (either a literal token or a vault reference) matches.
	 *
	 * Comparison is constant-time (`hash_equals`) over the resolved token
	 * value; no token leaks via logs.
	 *
	 * @param string $token Inbound bearer token.
	 *
	 * @return array<string, mixed>|null Matching abonnement, or null.
	 */
	private function resolveAbonnementByBearer(string $token): ?array {
		$rows = $this->registers->findAll(ZgwRegisterAccess::SCHEMA_ABONN, ['actief' => true]);
		foreach ($rows as $row) {
			if ((bool)($row['actief'] ?? false) === false) {
				continue;
			}

			$stored = (string)($row['callbackAuth'] ?? '');
			if ($stored === '') {
				continue;
			}

			$resolved = $this->api->resolveClientSecret($stored);
			if ($resolved === '') {
				$resolved = $stored;
			}

			if (hash_equals($resolved, $token) === true) {
				return $row;
			}
		}

		return null;
	}//end resolveAbonnementByBearer()

	/**
	 * Strip the "Bearer " prefix from an Authorization header value.
	 *
	 * @param string $headerValue Authorization header value.
	 *
	 * @return string Bare token or empty string.
	 */
	private static function extractBearer(string $headerValue): string {
		if ($headerValue === '') {
			return '';
		}

		if (stripos($headerValue, 'Bearer ') === 0) {
			return trim(substr($headerValue, 7));
		}

		return '';
	}//end extractBearer()

	/**
	 * Read the raw request body.
	 *
	 * Protected so unit tests can subclass and inject a fixture without
	 * touching `php://input`.
	 *
	 * @return string Body contents (possibly empty).
	 */
	protected function readRawBody(): string {
		$body = file_get_contents('php://input');
		if ($body !== false) {
			return $body;
		}

		return '';
	}//end readRawBody()
}//end class
